"""criar tabelas iniciais

Revision ID: 83b283ef083e
Revises: 
Create Date: 2025-05-06 10:21:17.312183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b283ef083e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance',
    sa.Column('insurance_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.CHAR(length=14), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('insurance_id')
    )
    op.create_index(op.f('ix_insurance_insurance_id'), 'insurance', ['insurance_id'], unique=False)
    op.create_index(op.f('ix_insurance_name'), 'insurance', ['name'], unique=False)
    op.create_table('patient',
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('cpf', sa.CHAR(length=11), nullable=False),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('gender', sa.Enum('Male', 'Female', 'Other', name='genderenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_patient_full_name'), 'patient', ['full_name'], unique=False)
    op.create_index(op.f('ix_patient_patient_id'), 'patient', ['patient_id'], unique=False)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Doctor', 'Admin', 'Secretary', 'Full', name='usertypeenum'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_table('doctor_patient',
    sa.Column('doctor_patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('associated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('doctor_patient_id'),
    sa.UniqueConstraint('user_id', 'patient_id', name='uq_doctor_patient')
    )
    op.create_index(op.f('ix_doctor_patient_doctor_patient_id'), 'doctor_patient', ['doctor_patient_id'], unique=False)
    op.create_table('patient_info',
    sa.Column('patient_info_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('file_identifier', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.PrimaryKeyConstraint('patient_info_id')
    )
    op.create_index(op.f('ix_patient_info_patient_info_id'), 'patient_info', ['patient_info_id'], unique=False)
    op.create_table('schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Scheduled', 'Confirmed', 'Canceled', 'Completed', name='appointmentstatusenum'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedule_appointment_date'), 'schedule', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_schedule_schedule_id'), 'schedule', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_schedule_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_appointment_date'), table_name='schedule')
    op.drop_table('schedule')
    op.drop_index(op.f('ix_patient_info_patient_info_id'), table_name='patient_info')
    op.drop_table('patient_info')
    op.drop_index(op.f('ix_doctor_patient_doctor_patient_id'), table_name='doctor_patient')
    op.drop_table('doctor_patient')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_patient_patient_id'), table_name='patient')
    op.drop_index(op.f('ix_patient_full_name'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_insurance_name'), table_name='insurance')
    op.drop_index(op.f('ix_insurance_insurance_id'), table_name='insurance')
    op.drop_table('insurance')
    # ### end Alembic commands ###
